export const actions = {
    FETCH_PRODUCT : "FETCH_PRODUCT",
    SET_PRODUCT : "SET_PRODUCT",
    INCREMENT_BASKET: "INCREMENT_BASKET",
    DECREMENT_BASKET: "DECREMENT_BASKET",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_CART: "REMOVE_CART",
    CALCULATE_CART_AMOUNT: "CALCULATE_CART_AMOUNTS"
}