export const actions = {
    FETCH_PRODUCT : "FETCH_PRODUCT",
    SET_PRODUCT : "SET_PRODUCT",
    INCREMENT_BASKET: "INCREMENT_BASKET",
    DECREMENT_BASKET: "DECREMENT_BASKET",
    RESET_BASKET: "RESET_BASKET",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_CART: "REMOVE_CART",
    CALCULATE_CART_AMOUNT: "CALCULATE_CART_AMOUNT",
    EMPTY_CART: "EMPTY_CART",
    DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
    DECREMENT_BASKET_QUANTITY: "DECREMENT_BASKET_QUANTITY"
}